[tool.black]
line-length = 120
[tool.isort]
profile = 'black'
line_length = 120
force_single_line = true
known_third_party = ["matplotlib", "munch", "numpy", "pandas", "requests", "scipy", "shapely", "pytz", "typing_extensions"]
skip_glob = [".env", "_viktor"]
[tool.pylint.'MASTER']
max-line-length=120
[tool.pylint.'MESSAGES CONTROL']
ignore=["_viktor"]
disable=[
    'R', 'C', 'W',  # Only show E (Error) warnings that pylint finds
    # Common exceptions (also for R, C and W codes) for VIKTOR apps
    'fixme',
    'import-error',
    'invalid-name',
    'line-too-long',
    'logging-fstring-interpolation',
    'method-could-be-funcion',
    'missing-docstring',
    'no-name-in-module',
    'no-else-return',
    'R0801',  # Similar lines in <x> files
    'raise-missing-from',
    'too-few-public-methods',
    'too-many-locals',
    'too-many-arguments',
    'too-many-branches',
    'too-many-instance-attributes',
    'unable-to-import',
    'unsubscriptable-object',
    'wrong-hanging-indentation',
    'wrong-import-order',
]
# We have switched of all warnings, explicitly add some
enable=[
    'bad-whitespace',
    'cyclic-import',
    'unused-import',
]
